version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - mosquitto:/mosquitto
      - mosquitto\data:/mosquitto/data
      - mosquitto\log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
  profiluxmqtt:
    build: .
    container_name: profiluxmqtt
    restart: unless-stopped
    environment:
      PROFILUX_HOST: "192.168.3.10"
      MQTT_HOST: "192.168.3.115"

